name: create-draft-release-action
description: Create a draft release
inputs:
  draft-release-name:
    description: Name of release to create
    required: true
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node24'
  main: 'dist/index.js'
