name: create-draft-release-action
description: Create a draft release
inputs:
  release-name:
    description: The name of release to create
    required: false
  release-name-file:
    description: The path to file of release name
    required: false
  body:
    description: The body of release
    required: false
  dry-run:
    description: If true, do not delete or create any release actually
    required: true
    default: 'false'
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
outputs:
  release-name:
    description: If created, the name of the release
  release-url:
    description: If created, the URL of the release
runs:
  using: 'node24'
  main: 'dist/index.js'
