name: create-draft-release-action
description: Create a draft release
inputs:
  release-name:
    description: Name of release to create
    required: false
  release-name-file:
    description: Path to file of release name
    required: false
  token:
    description: GitHub token
    required: true
    default: ${{ github.token }}
runs:
  using: 'node24'
  main: 'dist/index.js'
